=== Batbara/task-3-3-pagination-Talakh/src/main/resources/xml/movies.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema"
           targetNamespace="http://www.epam.tc.com/movies"
           xmlns:tns="http://www.epam.tc.com/movies"
           elementFormDefault="qualified">
    <xs:element name="movies">
        <xs:complexType>
            <xs:sequence>
                <xs:element name="movie" type="tns:Movie"
                            minOccurs="1"
                            maxOccurs="unbounded" />
            </xs:sequence>
        </xs:complexType>
    </xs:element>
    <xs:complexType name="Movie">
        <xs:sequence>
            <xs:element name="title" type="xs:string" />
            <xs:element name="genre" type="tns:Genre" />
            <xs:element name="year" type="tns:Year"/>
            <xs:element name="director" type="tns:Director" />
        </xs:sequence>
        <xs:attribute name="id" type="xs:positiveInteger" use="required" />
    </xs:complexType>
    <xs:simpleType name="Genre">
        <xs:restriction base="xs:string">
            <xs:enumeration value="comedy"/>
            <xs:enumeration value="drama"/>
            <xs:enumeration value="action"/>
            <xs:enumeration value="romance"/>
            <xs:enumeration value="crime"/>
            <xs:enumeration value="horror"/>
            <xs:enumeration value="fantasy"/>
        </xs:restriction>
    </xs:simpleType>
    <xs:simpleType name="Year">
        <xs:restriction base="xs:positiveInteger">
            <xs:minInclusive value="1920"/>
            <xs:maxInclusive value="2017"/>
        </xs:restriction>
    </xs:simpleType>
    <xs:complexType name="Director">
        <xs:sequence>
            <xs:element name="name" type="xs:string" />
            <xs:element name="surname" type="xs:string" />
        </xs:sequence>
    </xs:complexType>

</xs:schema>

=== Batbara/task-3-3-pagination-Talakh/movies.xml
<?xml version="1.0" encoding="UTF-8" standalone="yes"?>
<ns2:movies xmlns:ns2="http://www.epam.tc.com/movies" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://www.epam.tc.com/movies movies.xsd">
    <ns2:movie id="1">
        <ns2:title>The Avengers</ns2:title>
        <ns2:genre>action</ns2:genre>
        <ns2:year>2012</ns2:year>
        <ns2:director>
            <ns2:name>Joss</ns2:name>
            <ns2:surname>Wheadon</ns2:surname>
        </ns2:director>
    </ns2:movie>
    <ns2:movie id="2">
        <ns2:title>Real Genius</ns2:title>
        <ns2:genre>comedy</ns2:genre>
        <ns2:year>1985</ns2:year>
        <ns2:director>
            <ns2:name>Martha</ns2:name>
            <ns2:surname>Coolidge</ns2:surname>
        </ns2:director>
    </ns2:movie>
    <ns2:movie id="3">
        <ns2:title>Chinatown</ns2:title>
        <ns2:genre>drama</ns2:genre>
        <ns2:year>1974</ns2:year>
        <ns2:director>
            <ns2:name>Roman</ns2:name>
            <ns2:surname>Polanski</ns2:surname>
        </ns2:director>
    </ns2:movie>
    <ns2:movie id="4">
        <ns2:title>Veronika Decides to Die</ns2:title>
        <ns2:genre>drama</ns2:genre>
        <ns2:year>2009</ns2:year>
        <ns2:director>
            <ns2:name>Emily</ns2:name>
            <ns2:surname>Young</ns2:surname>
        </ns2:director>
    </ns2:movie>
    <ns2:movie id="5">
        <ns2:title>Poltergeist</ns2:title>
        <ns2:genre>horror</ns2:genre>
        <ns2:year>1974</ns2:year>
        <ns2:director>
            <ns2:name>Tobe</ns2:name>
            <ns2:surname>Hoope</ns2:surname>
        </ns2:director>
    </ns2:movie>
    <ns2:movie id="6">
        <ns2:title>Star Wars: Episode II</ns2:title>
        <ns2:genre>fantasy</ns2:genre>
        <ns2:year>1999</ns2:year>
        <ns2:director>
            <ns2:name>George</ns2:name>
            <ns2:surname>Lucas</ns2:surname>
        </ns2:director>
    </ns2:movie>
    <ns2:movie id="7">
        <ns2:title>The Lord of the Rings: The Two Towers</ns2:title>
        <ns2:genre>fantasy</ns2:genre>
        <ns2:year>2002</ns2:year>
        <ns2:director>
            <ns2:name>Peter</ns2:name>
            <ns2:surname>Jackson</ns2:surname>
        </ns2:director>
    </ns2:movie>
    <ns2:movie id="8">
        <ns2:title>EverAfter</ns2:title>
        <ns2:genre>romance</ns2:genre>
        <ns2:year>1998</ns2:year>
        <ns2:director>
            <ns2:name>Andy</ns2:name>
            <ns2:surname>Tennant</ns2:surname>
        </ns2:director>
    </ns2:movie>
    <ns2:movie id="9">
        <ns2:title>The Wedding Ringer</ns2:title>
        <ns2:genre>romance</ns2:genre>
        <ns2:year>2015</ns2:year>
        <ns2:director>
            <ns2:name>Jeremy</ns2:name>
            <ns2:surname>Garelick</ns2:surname>
        </ns2:director>
    </ns2:movie>
    <ns2:movie id="10">
        <ns2:title>A Fistful of Dollars</ns2:title>
        <ns2:genre>action</ns2:genre>
        <ns2:year>1964</ns2:year>
        <ns2:director>
            <ns2:name>Sergio</ns2:name>
            <ns2:surname>Leone</ns2:surname>
        </ns2:director>
    </ns2:movie>
    <ns2:movie id="11">
        <ns2:title>The Gift</ns2:title>
        <ns2:genre>crime</ns2:genre>
        <ns2:year>2000</ns2:year>
        <ns2:director>
            <ns2:name>Sam</ns2:name>
            <ns2:surname>Raimi</ns2:surname>
        </ns2:director>
    </ns2:movie>
    <ns2:movie id="12">
        <ns2:title>Confidence</ns2:title>
        <ns2:genre>crime</ns2:genre>
        <ns2:year>2003</ns2:year>
        <ns2:director>
            <ns2:name>James</ns2:name>
            <ns2:surname>Foley</ns2:surname>
        </ns2:director>
    </ns2:movie>
    <ns2:movie id="13">
        <ns2:title>Gorky Park</ns2:title>
        <ns2:genre>drama</ns2:genre>
        <ns2:year>1983</ns2:year>
        <ns2:director>
            <ns2:name>Michael</ns2:name>
            <ns2:surname>Apted</ns2:surname>
        </ns2:director>
    </ns2:movie>
    <ns2:movie id="14">
        <ns2:title>Stardust Memories</ns2:title>
        <ns2:genre>comedy</ns2:genre>
        <ns2:year>1980</ns2:year>
        <ns2:director>
            <ns2:name>Woody</ns2:name>
            <ns2:surname>Allen</ns2:surname>
        </ns2:director>
    </ns2:movie>
    <ns2:movie id="15">
        <ns2:title>Soapdish</ns2:title>
        <ns2:genre>romance</ns2:genre>
        <ns2:year>1991</ns2:year>
        <ns2:director>
            <ns2:name>Michael</ns2:name>
            <ns2:surname>Hoffman</ns2:surname>
        </ns2:director>
    </ns2:movie>
    <ns2:movie id="16">
        <ns2:title>Cat People</ns2:title>
        <ns2:genre>horror</ns2:genre>
        <ns2:year>1942</ns2:year>
        <ns2:director>
            <ns2:name>Jacques</ns2:name>
            <ns2:surname>Tourneur</ns2:surname>
        </ns2:director>
    </ns2:movie>
    <ns2:movie id="17">
        <ns2:title>The Rundown</ns2:title>
        <ns2:genre>action</ns2:genre>
        <ns2:year>2003</ns2:year>
        <ns2:director>
            <ns2:name>Peter</ns2:name>
            <ns2:surname>Berg</ns2:surname>
        </ns2:director>
    </ns2:movie>
    <ns2:movie id="18">
        <ns2:title>O Brother, Where Art Thou?</ns2:title>
        <ns2:genre>comedy</ns2:genre>
        <ns2:year>2000</ns2:year>
        <ns2:director>
            <ns2:name>Joel</ns2:name>
            <ns2:surname>Coen</ns2:surname>
        </ns2:director>
    </ns2:movie>
    <ns2:movie id="19">
        <ns2:title>Spider-Man</ns2:title>
        <ns2:genre>action</ns2:genre>
        <ns2:year>2002</ns2:year>
        <ns2:director>
            <ns2:name>Sam</ns2:name>
            <ns2:surname>Raimi</ns2:surname>
        </ns2:director>
    </ns2:movie>
    <ns2:movie id="20">
        <ns2:title>Beauty and the Beast</ns2:title>
        <ns2:genre>fantasy</ns2:genre>
        <ns2:year>2017</ns2:year>
        <ns2:director>
            <ns2:name>Bill</ns2:name>
            <ns2:surname>Condon</ns2:surname>
        </ns2:director>
    </ns2:movie>
</ns2:movies>
